name: Build IPA

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Archive
        run: |
          xcodebuild archive \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            -project mankai.xcodeproj \
            -scheme mankai \
            -configuration Release \
            -archivePath $PWD/build/mankai.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export IPA
        run: |
          mkdir -p Payload
          cp -r $PWD/build/mankai.xcarchive/Products/Applications/mankai.app Payload/
          zip -r mankai.ipa Payload/

      - name: Upload IPA
        uses: actions/upload-artifact@v6
        with:
          name: mankai-unsigned-${{ github.ref_name }}
          path: mankai.ipa
